execute as @s at @s anchored eyes positioned ^-3 ^-3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^-1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^0 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-3 ^3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^-1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^0 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-2 ^3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^-1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^0 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^2 ^3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^-1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^0 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^1 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^2 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^9 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^9.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^10 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^10.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^13.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^14 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^14.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^3 ^3 ^15 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air