execute as @s at @s anchored eyes positioned ^-1 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^-1 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^0 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^-1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^0 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^11 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^11.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^12 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^12.5 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air
execute as @s at @s anchored eyes positioned ^1 ^1 ^13 if block ~ ~ ~ typidoyun:sketch run setblock ~ ~ ~ air